export const CALENDAR_SELECT_DATE = 'CALENDAR_SELECT_DATE';
export const CALENDAR_SELECT_RANGE = 'CALENDAR_SELECT_RANGE';
export const CALENDAR_DESELECT = 'CALENDAR_DESELECT';
export const CALENDAR_RESET = 'CALENDAR_RESET';
