export const CLICK_PLACE_PICKER = 'CLICK_PLACEPICKER';
export const CLICK_SERVICE_POPUP = 'CLICK_SERVICE_POPUP';
export const CLICK_ADD_PAYMENT = 'CLICK_ADD_PAYMENT';
export const CLICK_ADD_VEHICLE = 'CLICK_ADD_VEHICLE';