export const LOCATION_GET_CURRENT = 'LOCATION_GET_CURRENT';
export const LOCATION_GET_CURRENT_SUCCESS = 'LOCATION_GET_CURRENT_SUCCESS';
export const LOCATION_GET_CURRENT_FAIL = 'LOCATION_GET_CURRENT_FAIL';
export const LOCATION_GET_CURRENT_ERROR = 'LOCATION_GET_CURRENT_ERROR';

export const LOCATION_SELECT = 'LOCATION_SELECT';
export const LOCATION_DESELECT = 'LOCATION_DESELECT';
