export const METADATA_GET_VEHICLE_MAKE = 'METADATA_GET_VEHICLE_MAKE';
export const METADATA_GET_VEHICLE_MAKE_SUCCESS = 'METADATA_GET_VEHICLE_MAKE_SUCCESS';
export const METADATA_GET_VEHICLE_MAKE_FAIL = 'METADATA_GET_VEHICLE_MAKE_FAIL';
export const METADATA_GET_VEHICLE_MAKE_ERROR = 'METADATA_GET_VEHICLE_MAKE_ERROR';

export const METADATA_GET_VEHICLE_MODEL = 'METADATA_GET_VEHICLE_MODEL';
export const METADATA_GET_VEHICLE_MODEL_SUCCESS = 'METADATA_GET_VEHICLE_MODEL_SUCCESS';
export const METADATA_GET_VEHICLE_MODEL_FAIL = 'METADATA_GET_VEHICLE_MODEL_FAIL';
export const METADATA_GET_VEHICLE_MODEL_ERROR = 'METADATA_GET_VEHICLE_MODEL_ERROR';

export const METADATA_GET_DISCOUNT = 'METADATA_GET_DISCOUNT';
export const METADATA_GET_DISCOUNT_SUCCESS = 'METADATA_GET_DISCOUNT_SUCCESS';
export const METADATA_GET_DISCOUNT_FAIL = 'METADATA_GET_DISCOUNT_FAIL';
export const METADATA_GET_DISCOUNT_ERROR = 'METADATA_GET_DISCOUNT_ERROR';
