export const METADATA_GET_DISCOUNT = 'METADATA_GET_DISCOUNT';
export const METADATA_GET_DISCOUNT_SUCCESS = 'METADATA_GET_DISCOUNT_SUCCESS';
export const METADATA_GET_DISCOUNT_FAIL = 'METADATA_GET_DISCOUNT_FAIL';
export const METADATA_GET_DISCOUNT_ERROR = 'METADATA_GET_DISCOUNT_ERROR';
