export const PAYMENT_ADD = 'PAYMENT_ADD';
export const PAYMENT_ADD_SUCCESS = 'PAYMENT_ADD_SUCCESS';
export const PAYMENT_ADD_FAIL = 'PAYMENT_ADD_FAIL';
export const PAYMENT_ADD_ERROR = 'PAYMENT_ADD_ERROR';

export const PAYMENT_DELETE = 'PAYMENT_DELETE';
export const PAYMENT_DELETE_SUCCESS = 'PAYMENT_DELETE_SUCCESS';
export const PAYMENT_DELETE_FAIL = 'PAYMENT_DELETE_FAIL';
export const PAYMENT_DELETE_ERROR = 'PAYMENT_DELETE_ERROR';

export const PAYMENT_UPDATE = 'PAYMENT_UPDATE';
export const PAYMENT_UPDATE_SUCCESS = 'PAYMENT_UPDATE_SUCCESS';
export const PAYMENT_UPDATE_FAIL = 'PAYMENT_UPDATE_FAIL';
export const PAYMENT_UPDATE_ERROR = 'PAYMENT_UPDATE_ERROR';

export const PAYMENT_GET_ALL = 'PAYMENT_GET_ALL';
export const PAYMENT_GET_ALL_SUCCESS = 'PAYMENT_GET_ALL_SUCCESS';
export const PAYMENT_GET_ALL_FAIL = 'PAYMENT_GET_ALL_FAIL';
export const PAYMENT_GET_ALL_ERROR = 'PAYMENT_GET_ALL_ERROR';
