export const PICKER_SHOW = 'PICKER_SHOW';
export const PICKER_HIDE = 'PICKER_HIDE';
export const PICKER_PICK_RESET = 'PICKER_PICK_RESET';

export const PICKER_PICK_VEHICLE_MAKE = 'PICKER_PICK_VEHICLE_MAKE';
export const PICKER_PICK_VEHICLE_MODEL = 'PICKER_PICK_VEHICLE_MODEL';
export const PICKER_PICK_VEHICLE_STATE = 'PICKER_PICK_VEHICLE_STATE';
export const PICKER_PICK_VEHICLE_COLOR = 'PICKER_PICK_VEHICLE_COLOR';
export const PICKER_PICK_VEHICLE_YEAR = 'PICKER_PICK_VEHICLE_YEAR';
