export const RESET_PASSWORD_VALIDATE_EMAIL = 'RESET_PASSWORD_VALIDATE_EMAIL';
export const RESET_PASSWORD_VALIDATE_EMAIL_SUCCESS = 'RESET_PASSWORD_VALIDATE_EMAIL_SUCCESS';
export const RESET_PASSWORD_VALIDATE_EMAIL_ERROR = 'RESET_PASSWORD_VALIDATE_EMAIL_ERROR';
export const RESET_PASSWORD_VALIDATE_EMAIL_FAIL = 'RESET_PASSWORD_VALIDATE_EMAIL_FAIL';

export const RESET_PASSWORD_VALIDATE_TOKEN = 'RESET_PASSWORD_VALIDATE_TOKEN';
export const RESET_PASSWORD_VALIDATE_TOKEN_SUCCESS = 'RESET_PASSWORD_VALIDATE_TOKEN_SUCCESS';
export const RESET_PASSWORD_VALIDATE_TOKEN_ERROR = 'RESET_PASSWORD_VALIDATE_TOKEN_ERROR';
export const RESET_PASSWORD_VALIDATE_TOKEN_FAIL = 'RESET_PASSWORD_VALIDATE_TOKEN_FAIL';

export const RESET_PASSWORD_NEW_PASSWORD = 'RESET_PASSWORD_NEW_PASSWORD';
export const RESET_PASSWORD_NEW_PASSWORD_SUCCESS = 'RESET_PASSWORD_NEW_PASSWORD_SUCCESS';
export const RESET_PASSWORD_NEW_PASSWORD_ERROR = 'RESET_PASSWORD_NEW_PASSWORD_ERROR';
export const RESET_PASSWORD_NEW_PASSWORD_FAIL = 'RESET_PASSWORD_NEW_PASSWORD_FAIL';
