export const RESIDENT_LOCATION = 'RESIDENT_LOCATION';
export const RESIDENT_SERVICE = 'RESIDENT_SERVICE';
export const RESIDENT_PAYMENT = 'RESIDENT_PAYMENT';
export const RESIDENT_CONFIRM = 'RESIDENT_CONFIRM';
export const RESIDENT_PLACE_ORDER = 'RESIDENT_PLACE_ORDER';
