export const SERVICE_GET_ALL = 'SERVICE_GET_ALL';
export const SERVICE_GET_ALL_SUCCESS = 'SERVICE_GET_ALL_SUCCESS';
export const SERVICE_GET_ALL_FAIL = 'SERVICE_GET_ALL_FAIL';
export const SERVICE_GET_ALL_ERROR = 'SERVICE_GET_ALL_ERROR';

export const SERVICE_SHOW = 'SERVICE_SHOW';
export const SERVICE_HIDE = 'SERVICE_HIDE';

export const SERVICE_SELECT = 'SERVICE_SELECT';
export const SERVICE_DESELECT = 'SERVICE_DESELECT';

export const SERVICE_GET_ALL_RESERVATION = 'SERVICE_GET_ALL_RESERVATION';
export const SERVICE_GET_ALL_RESERVATION_SUCCESS = 'SERVICE_GET_ALL_RESERVATION_SUCCESS';
export const SERVICE_GET_ALL_RESERVATION_FAIL = 'SERVICE_GET_ALL_RESERVATION_FAIL';
export const SERVICE_GET_ALL_RESERVATION_ERROR = 'SERVICE_GET_ALL_RESERVATION_ERROR';

export const SERVICE_RESERVE = 'SERVICE_RESERVE';
export const SERVICE_RESERVE_SUCCESS = 'SERVICE_RESERVE_SUCCESS';
export const SERVICE_RESERVE_FAIL = 'SERVICE_RESERVE_FAIL';
export const SERVICE_RESERVE_ERROR = 'SERVICE_RESERVE_ERROR';

export const SERVICE_CANCEL_RESERVATION = 'SERVICE_CANCEL_RESERVATION';
export const SERVICE_CANCEL_RESERVATION_SUCCESS = 'SERVICE_CANCEL_RESERVATION_SUCCESS';
export const SERVICE_CANCEL_RESERVATION_FAIL = 'SERVICE_CANCEL_RESERVATION_FAIL';
export const SERVICE_CANCEL_RESERVATION_ERROR = 'SERVICE_CANCEL_RESERVATION_ERROR';
