export const SERVICE_GET_ALL = 'SERVICE_GET_ALL';
export const SERVICE_GET_ALL_SUCCESS = 'SERVICE_GET_ALL_SUCCESS';
export const SERVICE_GET_ALL_FAIL = 'SERVICE_GET_ALL_FAIL';
export const SERVICE_GET_ALL_ERROR = 'SERVICE_GET_ALL_ERROR';

export const SERVICE_SELECT = 'SERVICE_SELECT';
export const SERVICE_DESELECT = 'SERVICE_DESELECT';