export const VEHICLE_GET_MAKE = 'VEHICLE_GET_MAKE';
export const VEHICLE_GET_MAKE_SUCCESS = 'VEHICLE_GET_MAKE_SUCCESS';
export const VEHICLE_GET_MAKE_ERROR = 'VEHICLE_GET_MAKE_ERROR';
export const VEHICLE_GET_MAKE_FAIL = 'VEHICLE_GET_MAKE_FAIL';

export const VEHICLE_GET_MODEL = 'VEHICLE_GET_MODEL';
export const VEHICLE_GET_MODEL_SUCCESS = 'VEHICLE_GET_MODEL_SUCCESS';
export const VEHICLE_GET_MODEL_ERROR = 'VEHICLE_GET_MODEL_ERROR';
export const VEHICLE_GET_MODEL_FAIL = 'VEHICLE_GET_MODEL_FAIL';

export const VEHICLE_ADD = 'VEHICLE_ADD';
export const VEHICLE_ADD_SUCCESS = 'VEHICLE_ADD_SUCCESS';
export const VEHICLE_ADD_ERROR = 'VEHICLE_ADD_ERROR';
export const VEHICLE_ADD_FAIL = 'VEHICLE_ADD_FAIL';

export const VEHICLE_DELETE = 'VEHICLE_DELETE';
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS';
export const VEHICLE_DELETE_ERROR = 'VEHICLE_DELETE_ERROR';
export const VEHICLE_DELETE_FAIL = 'VEHICLE_DELETE_FAIL';

export const VEHICLE_UPDATE = 'VEHICLE_UPDATE';
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS';
export const VEHICLE_UPDATE_ERROR = 'VEHICLE_UPDATE_ERROR';
export const VEHICLE_UPDATE_FAIL = 'VEHICLE_UPDATE_FAIL';

export const VEHICLE_GET_ALL = 'VEHICLE_GET_ALL';
export const VEHICLE_GET_ALL_SUCCESS = 'VEHICLE_GET_ALL_SUCCESS';
export const VEHICLE_GET_ALL_ERROR = 'VEHICLE_GET_ALL_ERROR';
export const VEHICLE_GET_ALL_FAIL = 'VEHICLE_GET_ALL_FAIL';
