export const WORK_FLOW_BACK = 'WORK_FLOW_BACK';
export const WORK_FLOW_START = 'WORK_FLOW_START';
export const WORK_FLOW_LOCATION = 'WORK_FLOW_LOCATION';
export const WORK_FLOW_ORDER = 'WORK_FLOW_ORDER';
export const WORK_FLOW_CALENDAR = 'WORK_FLOW_CALENDAR';
export const WORK_FLOW_SIGN = 'WORK_FLOW_SIGN';
export const WORK_FLOW_SERVICE = 'WORK_FLOW_SERVICE';
export const WORK_FLOW_SCANNER = 'WORK_FLOW_SCANNER';