source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'egobie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for egobie
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    # 'RCTActionSheet',
    # 'RCTAnimation',
    # 'RCTGeolocation',
    # 'RCTImage',
    # 'RCTLinkingIOS',
    # 'RCTNetwork',
    # 'RCTSettings',
    # 'RCTText',
    # 'RCTVibration',
    # 'RCTWebSocket'
  ]

  # Comment this line if you do not want to support GoogleMaps on iOS
  pod 'GoogleMaps'
  pod 'Google/SignIn'

end
